from .connect_page import ConnectPage
from .edit_profile_page import EditProfilePage
from .following_page import FollowingPage
from .home_page import HomePage
from .login_page import LoginPage
from .logout_page import LogoutPage
from .main_page import MainPage
from .profile_edit_media_page import EditMediaPage
from .profile_page import ProfilePage
